include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/misc/mediatek/ppm/inc \
             -I$(srctree)/drivers/misc/mediatek/ppm/src/mach/$(MTK_PLATFORM)

# power state settings
obj-y += mt_ppm_power_state.o
